In [1]:
import MDAnalysis as md
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [10]:
mc10 = md.Universe("PDI.1.forces.nMC10.xyz")
mc100 = md.Universe("PDI.1.forces.nMC100.xyz")
mc1000 = md.Universe("PDI.1.forces.nMC1000.xyz")
mc10000 = md.Universe("PDI.1.forces.nMC10000.xyz")
mc100000 = md.Universe("PDI.1.forces.nMC100000.xyz")

In [3]:
np.sum(mc10.atoms.positions,axis=0)

array([  3.16007996,   0.2904458 ,  11.16970921], dtype=float32)

In [4]:
np.sum(mc100.atoms.positions,axis=0)

array([-5.08800936,  0.87844324,  1.71298051], dtype=float32)

In [5]:
np.sum(mc1000.atoms.positions,axis=0)

array([ 1.52053022,  0.99411887,  1.00809777], dtype=float32)

In [6]:
np.sum(mc10000.atoms.positions,axis=0)

array([ 0.0299111 ,  0.16288389, -0.26235509], dtype=float32)

In [7]:
np.sum(mc100000.atoms.positions,axis=0)

array([ 0.08087006, -0.05139795,  0.05537504], dtype=float32)

In [9]:
np.sum(mc100000.atoms.positions,axis=0)

array([ 0.08086503, -0.05137077,  0.05542492], dtype=float32)

In [11]:
np.sum(mc100000.atoms.positions,axis=0)

array([ 0.08086011, -0.05137393,  0.05541914], dtype=float32)